### ISSUE TITLE
Orderable Rows not Sorting many_many relationship with extraFields

### ISSUE THREAD

**Issue by pxwee5** [symbiote/silverstripe-gridfieldextensions#252]
I have a many_many relationship with extraField `SortOrder`. 

My gridfield is a `GridFieldConfig_RelationEditor` with `addComponent(new GridFieldOrderableRows('SortOrder')` set. 

However when I tried to drag to sort my relations, the records reordered notification did pop
![image](https://user-images.githubusercontent.com/14123790/37881513-d916d30e-30f5-11e8-965b-e3d6c3ee2acb.png)
But the database `SortOrder` field do not change accordingly. 

Both the DataObjects are versioned, with the new SS4 versioned extension. 

EDIT: Only fix was to use https://github.com/UndefinedOffset/SortableGridField.

**Comment by robbieaverill** [comment]
@pxwee5 can you please provide a Gist with some example code to show your setup?

**Comment by pxwee5** [comment]
ElementGrid
```
    private static $many_many = [
        'Columns' => Column::class
    ];

    private static $many_many_extraFields = [
        'Columns' => array(
          'SortOrder' => 'Int'
        )
    ];

    private function getGridFields()
    {
        $config = GridFieldConfig_RecordEditor::create();

        $config
            ->removeComponentsByType(GridFieldSortableHeader::class)
            ->removeComponentsByType(GridFieldToolbarHeader::class)
            ->removeComponentsByType(GridFieldPageCount::class)
            ->addComponent(new GridFieldTitleHeader())
            ->getComponentByType(GridFieldDetailForm::class)
            ->setItemRequestClass(VersionedGridFieldItemRequest::class);

        if ($this->ID) {
            $config->addComponent(new GridFieldOrderableRows('SortOrder'));
        }

        return [
            new GridField('Columns', 'All Content Types', $this->Columns(), $config)
        ];
    }


    public function getCMSFields()
    {
        $fields = parent::getCMSFields();

        $fields->addFieldsToTab('Root.Main.ContentSet.Main', $this->getGridFields());

        return $fields;
    }
```

**Comment by ishannz** [comment]
Hey @robbieaverill, we have found a similar issue. It looks related to `GridFieldOrderableRows::reorderItems()` which on [line 587](https://github.com/symbiote/silverstripe-gridfieldextensions/blob/master/src/GridFieldOrderableRows.php#L587) uses a data object directly instead of setting the field on the many_many relation. This obviously doesn't work because while the class (e.g. `Page`) might be versioned, the many-many relationship between the two isn't, so it's trying to set a value on Page (`SortOrder`) which doesn't exist, rather than setting it on the `Columns.SortOrder` field.

**Comment by NightJar** [comment]
Hey crew, just a quick question;
Is everyone using `4.0.x` or `4.1.x` for SS core?
@pxwee5 @ishannz @thats4shaw

**Comment by thats4shaw** [comment]
`silverstripe/framework 4.1.0` and `symbiote/silverstripe-gridfieldextensions 3.1.1`.

**Comment by ishannz** [comment]
@NightJar, im using CWP 2.0.0-rc-3  and gridfieldextensions 3.1.1

**Comment by danaenz** [comment]
`silverstripe/framework 4.1.0` and `symbiote/silverstripe-gridfieldextensions 3.1.1`

**Comment by NightJar** [comment]
Sweet thanks team :) That'll be great help in tracking this down.

**Comment by thats4shaw** [comment]
I can confirm @NightJar.  I've gotten into the habit of just versioning all objects nowadays.

**Comment by danaenz** [comment]
Thanks @NightJar , can confirm I'm using the many_many with two versioned objects.

I think I should be using many_many_through anyway - might test this out when I get a chance.

**Comment by NightJar** [comment]
In order to make the re-ordering function as expected (in case someone needs this sooner than I can find time to finish it), I should imagine it would be a case of adding similar logic to the existing examples in my links above (testing for `ManyManyThroughList`) and then ordering the intermediary object directly as with what happens for the `has_many` (in the case for versioned objects).

I would hope at that point some `$owns` declarations would tidy the entire thing off and publish the new order when the 'parent' page is (in the case of the CWP related pages work). If not there could be some tricky logic around `onAfterPublish` or the like, but I feel like this should be possible. If not, I would log an issue against framework about `owns`ing a ManyManyThrough relationship (particularly around the extra fields logic).

**Comment by NightJar** [comment]
Hey team, I've got a working concept in #260 - the caveat being as described; one must define a `many_many through` type relationship, as opposed to the simple `many_many`.

Would anyone care to test and report back in that PR?
