### ISSUE TITLE
GridFieldOrderableRows - No support for ManyManyThroughList

### ISSUE THREAD

**Issue by mfendeksilverstripe** [symbiote/silverstripe-gridfieldextensions#254]
There is no support in `GridFieldOrderableRows` for `ManyManyThroughList`. Note that `ManyManyThroughList` doesn't extend `ManyManyList`. 

We need to find all cases where a `ManyManyList` is handled and handle `ManyManyThroughList` in that place as well.

**Comment by robbieaverill** [comment]
Damn, it would've been nice if ManyManyThroughList extended ManyManyList.

**Comment by tractorcow** [comment]
It doesn't because the classes aren't substitutable for one another; There are similarities between the two, but they do have separate behaviour that doesn't always imply one is a superset of another. For now you should just check either case.

It's about 5 hours of work IMO to fix and test.

**Comment by tractorcow** [comment]
We could have an interface for "relation with getExtraFields" I guess instead of a core ManyManyList.

**Comment by dhensby** [comment]
OK - I've looked through this and the primary issue is that `ManyManyThroughList` (MMTL) doesn't share inheritance or an API with `ManyManyList`. MMTL isn't really fit for purpose because all the knowledge is in the `ManyManyThroughQueryManipulator` which is not accessible outside the MMTL class and the information it holds is not exposed in any way, either.

The most important API we need on `ManyManyThroughList` is `getJoinTable` which is used to create the query that writes the sorts.

I've added a PR to core to add this (https://github.com/silverstripe/silverstripe-framework/pull/8065)

I've added a PR to this repo (#258) to add MMTL support, which is dependant on the above framework PR.

**Comment by mfendeksilverstripe** [comment]
Nice one, will have a look at it.

**Comment by tractorcow** [comment]
Ok https://github.com/silverstripe/silverstripe-framework/pull/8065 is merged

**Comment by NightJar** [comment]
#260 resolves this
