### ISSUE TITLE
GridFieldOrderableRows issue with ManyMany relation to versioned class.

### ISSUE THREAD

**Issue by itarsa** [symbiote/silverstripe-gridfieldextensions#266]
When trying to sort ManyMany relation to versioned class with extraField added to relation, script ignores extraField and tries to change Versioned record instead. Conditional statement if (!$isVersioned) [GridFieldOrderableRows.php line 607] assumes that many many relations are only possible with non versioned classes.

**Comment by NightJar** [comment]
Hi @itarsa - can you please provide version information with your issue? If you are unsure how to obtain this info, it should be in your projects list of installed dependencies which can be seen via `composer show`

**Comment by itarsa** [comment]
Found this issue with GridfieldExtensions 3.1.1 (GridFieldOrderableRows.php line 548).

**Comment by NightJar** [comment]
Hi @itarsa - yes the versioned check exists on that line at that version, however it seems like you may have overlooked the `else` that follows it: https://github.com/symbiote/silverstripe-gridfieldextensions/blob/3.1.1/src/GridFieldOrderableRows.php#L575

https://github.com/symbiote/silverstripe-gridfieldextensions/blob/6d8b41ee5a0b0f1b07215f5bf146c07a78ef61fe/src/GridFieldOrderableRows.php#L575-L587

This is normal, and will work - provided that the `SS_List` is a `ManyManyList` (a subclass of `RelationList`), as this is where `extraFields` are allowed for. If the list has been obtained in a different way (a custom getter, or `RelatedThing::get()->Filter('Relation.ID', $this->ID)` perhaps) then extraFields won't be added to (or saved from) the object.

**Comment by NightJar** [comment]
Sorry, in my previous answer I was focused on the point that whether a relationship is many_many or not at that point (inside the `else`) should be irrelevant as the sort field should be able to be accessed and written regardless. However in reading I skipped over the `$class::get()->byID()` bit which does _not_ use the provided list as a source of truth, meaning the extra field will indeed be missing (and thus not saved). You're right there, sorry.

The logic here is set up only to support `has_many` relationships to versioned objects. I think that is fine as there's a consideration to be made around ordering unpublished items, and the mismatch in that re-ordering draft items will instantaneously also reorder the live items (as the extraField that controls the sort is _not_ versioned).

This has been fixed in [3.2.0](https://github.com/symbiote/silverstripe-gridfieldextensions/releases/tag/3.2.0) - I recommend you install this to resolve your issue, as it deals with other issues around sorting versioned items (actually using the instances in the provided list), and in particular with many_many relationships (such as those in the previous paragraph).
