### ISSUE TITLE
Move to prev/next page functionality is broken

### ISSUE THREAD

**Issue by lozcalver** [symbiote/silverstripe-gridfieldextensions#307]
It looks to me like `GridFieldOrderableRows::reorderItems()` was updated from taking a list of IDs and putting them in order, to taking an associative array or pre-ordered sort/id values.

`handleMovetoPage()` currently generates an indexed array of IDs that are in the correct order, but as they don’t have any sort values `reorderItems()` doesn’t deal with them properly.

## PRs
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/308

**Comment by joechamberlain1** [comment]
Hi, I'm still having an issue with this it seems the grid field order is still not behaving the way it should. Currently using silverstripe version 4.12 and PHP 8.0. 

In a customised grid field as shown in the clip below shows some interesting behaviour. This grid has 3 pages of grid field items, all of which are given a letter as a title. Trying to move the 'z' grid to the next page moves it to the last page and also changes the order of most of the exisiting grid items. The 'z' grid item has also been moved to page 3 instead of 2. Moving it back to page 2 seems to work but then the item has moved slightly above the mouse and can't be dropped onto the page arrows.

https://user-images.githubusercontent.com/22623713/218360338-7e882720-3b1b-4b2e-a2f4-e5c79a1acd32.mov

**Comment by GuySartorelli** [comment]
PR merged. This will be automatically tagged by GitHub actions
