### ISSUE TITLE
GridFieldAddNewMultiClass and GridFieldAddNewInlineButton  does not work togther

### ISSUE THREAD

**Issue by Lukin-zz** [symbiote/silverstripe-gridfieldextensions#90]
it produces a record with the parent class.
no class-selection is available

**Comment by SilbinaryWolf** [comment]
That's because they're two very different components. If you want this kind of functionality, I'd suggest using the GridFieldInlineButton with GridFieldEditableColumns, and then exposing the 'ClassName' as the first field.

For an example, look at how User Defined Forms 3.0 does it here:
[https://github.com/silverstripe/silverstripe-userforms/tree/3.0](https://github.com/silverstripe/silverstripe-userforms/tree/3.0)
